// Gugu Plus SaaS UI Design/src/app/components/ItemCard.tsx
import { Link } from "react-router";
import { 
  TrendingUp, 
  TrendingDown, 
  Minus, 
  Clock, 
  Bell,
  BellOff
} from "lucide-react";

interface TrackedItem {
  id: string;
  title: string;
  site: string;
  currentPrice: number;
  currency: string;
  priceChange: number;
  changeType: "up" | "down" | "same";
  lastChecked: string;
  trackingFrequency: string;
  alertEnabled: boolean;
  imageUrl?: string;
}

interface ItemCardProps {
  item: TrackedItem;
}

const siteColors: Record<string, { bg: string; text: string }> = {
  Amazon: { bg: '#fef3e8', text: '#c97d32' },
  eBay: { bg: '#fef9e8', text: '#c9a832' },
  AliExpress: { bg: '#fee8e8', text: '#c93232' },
  Taobao: { bg: '#fef0e8', text: '#c96332' },
  "1688": { bg: '#fef5e8', text: '#c99532' },
};

export function ItemCard({ item }: ItemCardProps) {
  const siteStyle = siteColors[item.site] || { bg: '#f7f6f3', text: '#6b6b65' };

  return (
    <Link
      to={`/item/${item.id}`}
      className="block bg-white rounded-2xl p-6 transition-all hover:shadow-lg"
      style={{ border: '1px solid rgba(45, 45, 42, 0.06)' }}
    >
      <div className="flex gap-6">
        {/* Product Image */}
        {item.imageUrl && (
          <div className="w-28 h-28 rounded-xl flex-shrink-0 overflow-hidden" style={{ backgroundColor: '#f7f6f3' }}>
            <img
              src={item.imageUrl}
              alt={item.title}
              className="w-full h-full object-cover"
            />
          </div>
        )}

        {/* Content */}
        <div className="flex-1 min-w-0">
          {/* Title & Site Badge */}
          <div className="flex items-start gap-3 mb-3">
            <h3 className="text-base font-medium line-clamp-2 flex-1" style={{ color: '#1a1a17', lineHeight: '1.5' }}>
              {item.title}
            </h3>
            <span
              className="px-2.5 py-1 rounded-lg text-xs font-medium flex-shrink-0"
              style={{ backgroundColor: siteStyle.bg, color: siteStyle.text }}
            >
              {item.site}
            </span>
          </div>

          {/* Price & Change */}
          <div className="flex items-baseline gap-3 mb-4">
            <span className="text-2xl font-semibold" style={{ color: '#1a1a17' }}>
              {item.currency}{item.currentPrice.toFixed(2)}
            </span>
            {item.changeType !== "same" && (
              <div
                className="flex items-center gap-1.5 text-sm font-medium"
                style={{ color: item.changeType === "down" ? '#5aad9c' : '#d4183d' }}
              >
                {item.changeType === "down" ? (
                  <TrendingDown className="w-4 h-4" strokeWidth={2} />
                ) : (
                  <TrendingUp className="w-4 h-4" strokeWidth={2} />
                )}
                <span>
                  {item.currency}{Math.abs(item.priceChange).toFixed(2)}
                </span>
              </div>
            )}
            {item.changeType === "same" && (
              <div className="flex items-center gap-1.5 text-sm" style={{ color: '#6b6b65' }}>
                <Minus className="w-4 h-4" strokeWidth={2} />
                <span>No change</span>
              </div>
            )}
          </div>

          {/* Meta Info */}
          <div className="flex items-center gap-6 text-sm" style={{ color: '#6b6b65' }}>
            <div className="flex items-center gap-1.5">
              <Clock className="w-4 h-4" strokeWidth={2} />
              <span>Checked {item.lastChecked}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span>•</span>
              <span>Every {item.trackingFrequency}</span>
            </div>
            <div className="flex items-center gap-1.5">
              {item.alertEnabled ? (
                <>
                  <Bell className="w-4 h-4" strokeWidth={2} />
                  <span>Alert on</span>
                </>
              ) : (
                <>
                  <BellOff className="w-4 h-4" strokeWidth={2} />
                  <span>Alert off</span>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    </Link>
  );
}

// src/lib/components/ItemCard.svelte
<script lang="ts">
	import type { TrackedItem } from '$lib/types';

	let { item }: { item: TrackedItem } = $props();

	let imgError = $state(false);

	const siteColors: Record<string, string> = {
		Amazon: 'bg-orange-50 text-orange-700',
		Taobao: 'bg-red-50 text-red-700',
		eBay: 'bg-blue-50 text-blue-700',
		AliExpress: 'bg-rose-50 text-rose-700',
		'1688': 'bg-amber-50 text-amber-700'
	};

	const siteBadgeClass = $derived(siteColors[item.site] ?? 'bg-zinc-100 text-zinc-600');
</script>

<a href="/items/{item.id}" class="flex items-center gap-3 rounded-xl border border-zinc-200 bg-white px-3 py-3 transition hover:border-zinc-300 hover:shadow-sm sm:gap-4 sm:px-4">
	<!-- Image -->
	<div class="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-zinc-100 sm:size-14">
		{#if !imgError && item.imageUrl}
			<img
				src={item.imageUrl}
				alt={item.title}
				class="size-full object-cover"
				onerror={() => (imgError = true)}
			/>
		{:else}
			<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="size-5 text-zinc-300 sm:size-6" aria-hidden="true">
				<path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
			</svg>
		{/if}
	</div>

	<!-- Title & site -->
	<div class="min-w-0 flex-1">
		<p class="line-clamp-2 text-sm font-medium text-zinc-900">{item.title}</p>
		<div class="mt-1.5">
			<span class="rounded-md px-1.5 py-0.5 text-xs font-medium {siteBadgeClass}">
				{item.site}
			</span>
		</div>
	</div>

	<!-- Chevron -->
	<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="size-4 shrink-0 text-zinc-300" aria-hidden="true">
		<path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
	</svg>
</a>
